sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.41
    y: 0.0
    z: 0.91
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 0.515
    y: 0.0
    z: 0.24
    roll: 3.14159265359
    pitch: 0.0
    yaw: 3.14159265359